const BlockColor = {
    BOUNDARY: -1,
    RED: 1,
    BLUE: 2,
    YELLOW: 3,
}

const PieceRotation = {
    RIGHT: 0,
    DOWN: 1,
    LEFT: 2,
    UP: 3,
}

const WIDTH = 16
const HEIGHT = 20

const WELL_COLOR = 0x101010
const CAMERA_LIGHT_INTENSITY = 3
const PIECE_LIGHT_INTENSITY = 1
const PIECE_LIGHT_DISTANCE = 10

const WELL_DEPTH = 3
const WELL_WALL_WIDTH = 1
const PIECE_DEPTH = 0.5
const FALLING_SPEED = 3
const FALLING_ACCELERATED_SPEED = 25

const INPUT_DELAY_BEFORE_AUTO_MOVE = 0.3
const INPUT_AUTO_MOVE_FREQUENCY = 30

const ANIMATION_ROTATE_TIME = 0.1
const ANIMATION_MOVE_TIME = 0.1
const ANIMATION_SHAKE_TIME = 0.05
const ANIMATION_SHAKE_STEPS = 6
const ANIMATION_SHAKE_MAGNITUDE = 0.3
